#!/bin/sh
module="short"
device="short"

# invoke rmmod with all arguments we got
/sbin/rmmod $module $* || exit 1

# Remove stale nodes

rm -f /dev/${device}[0-7] /dev/${device}[0-7][ps] \
    /dev/${device}int /dev/${device}print





